<a href="https://colab.research.google.com/github/ramprasathasokan/Microsoft-Malware-Prediction-Using-CatBoost/blob/master/MMP_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [0]:
!pip install catboost
!pip install "dask[dataframe]"

Requirement already satisfied: catboost in /usr/local/lib/python3.6/dist-packages (0.18)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from catboost) (1.3.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from catboost) (1.12.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (1.17.3)
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (0.25.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (from catboost) (4.1.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from catboost) (3.1.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.0->catboost) (2.6.1)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly->catboost) (1.3.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (2.4.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (1.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from kiwisolver>=1.0.1->matplotlib->catboost) (41.4.0)
Requirement already satisfied: dask[dataframe] in /usr/local/lib/python3.6/dist-packages (1.1.5)
Requirement already satisfied: partd>=0.3.8; extra == "dataframe" in /usr/local/lib/python3.6/dist-packages (from dask[dataframe]) (1.0.0)
Requirement already satisfied: toolz>=0.7.3; extra == "dataframe" in /usr/local/lib/python3.6/dist-packages (from dask[dataframe]) (0.10.0)
Requirement already satisfied: numpy>=1.11.0; extra == "dataframe" in /usr/local/lib/python3.6/dist-packages (from dask[dataframe]) (1.17.3)
Requirement already satisfied: cloudpickle>=0.2.1; extra == "dataframe" in /usr/local/lib/python3.6/dist-packages (from dask[dataframe]) (0.6.1)
Requirement already satisfied: pandas>=0.19.0; extra == "dataframe" in /usr/local/lib/python3.6/dist-packages (from dask[dataframe]) (0.25.2)
Requirement already satisfied: locket in /usr/local/lib/python3.6/dist-packages (from partd>=0.3.8; extra == "dataframe"->dask[dataframe]) (0.2.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.19.0; extra == "dataframe"->dask[dataframe]) (2.6.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.19.0; extra == "dataframe"->dask[dataframe]) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas>=0.19.0; extra == "dataframe"->dask[dataframe]) (1.12.0)

In [0]:
train_final_path = '/content/gdrive/My Drive/kaggle/ms/train/train_final.csv'
test_final_path = '/content/gdrive/My Drive/kaggle/ms/test/test_final.csv'

In [0]:
from catboost import CatBoostClassifier
from catboost import Pool
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import dask.dataframe as dd
import pickle
import gc
import warnings
warnings.filterwarnings("ignore")

gc.enable()

In [0]:
def convert_types(df):
    # Convert data types to reduce memory
    for c in df:
        col_type = str(df[c].dtypes)
        numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
        
        # Convert objects to category
        if col_type == 'object':
            df[c] = df[c].astype('category')
        
        # numerics
        elif col_type in numerics:
            c_min = df[c].min()
            c_max = df[c].max()
            if col_type[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[c] = df[c].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[c] = df[c].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[c] = df[c].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[c] = df[c].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[c] = df[c].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[c] = df[c].astype(np.float32)
                else:
                    df[c] = df[c].astype(np.float64)  
        
    return df

In [0]:
ddf = dd.read_csv(train_final_path)
gc.collect()
train = ddf.compute()
gc.collect()
train = convert_types(train)

In [0]:
ddf = dd.read_csv(test_final_path)
gc.collect()
test = ddf.compute()
gc.collect()
test = convert_types(test)

In [0]:
target = 'HasDetections'
data_id = 'MachineIdentifier'

In [0]:
train.shape

(8921483, 80)

In [0]:
test.shape

(7853253, 80)

In [0]:
unimportant_features = ['Census_IsTouchEnabled',
 'HasTpm',
 'Census_IsVirtualDevice',
 'SMode',
 'Census_IsPenCapable',
 'Platform',
 'Census_ProcessorManufacturerIdentifier',
 'Census_IsAlwaysOnAlwaysConnectedCapable',
 'Census_IsPortableOperatingSystem',
 'OsVer',
 'Census_DeviceFamily',
 'index']

In [0]:
train = train.drop(columns = unimportant_features)

In [0]:
train.shape

(8921483, 68)

In [0]:
test = test.drop(columns = unimportant_features)

In [0]:
test.shape

(7853253, 68)

In [0]:
train_labels = np.array(train[target].astype(np.int8)).reshape((-1, ))

In [0]:
train = train.drop(columns = [target, data_id])

In [0]:
test_ids = list(test[data_id])

In [0]:
test = test.drop(columns = [target, data_id])

In [0]:
cat_features = ['OsPlatformSubRelease',
 'Census_MDC2FormFactor_new',
 'Census_FlightRing',
 'Census_PrimaryDiskTypeName',
 'Census_OSSkuName',
 'Census_OSBranch',
 'SkuEdition',
 'Census_OSArchitecture',
 'Census_OSEdition',
 'Census_GenuineStateName',
 'Processor',
 'SmartScreen',
 'Census_OSInstallTypeName',
 'Census_OSWUAutoUpdateOptionsName',
 'Census_ChassisTypeName',
 'Census_MDC2FormFactor',
 'Census_ActivationChannel',
 'Census_PowerPlatformRoleName',
 'Census_InternalPrimaryDiagonalDisplaySizeInInches',
 'Census_ProcessorCoreCount',
 'Census_HasOpticalDiskDrive',
 'Census_IsSecureBootEnabled',
 'Firewall',
 'IsProtected',
 'IsSxsPassiveMode',
 'Wdft_IsGamer',
 'monitor_dims',
 'SmartScreen_AVProductsInstalled']

In [0]:
for i in cat_features :
  if(train[i].dtype == np.float16):
    train[i] = train[i].round(0)
    train[i] = train[i].astype('int16')

In [0]:
train[cat_features].dtypes

OsPlatformSubRelease                                  int8
Census_MDC2FormFactor_new                             int8
Census_FlightRing                                     int8
Census_PrimaryDiskTypeName                            int8
Census_OSSkuName                                      int8
Census_OSBranch                                       int8
SkuEdition                                            int8
Census_OSArchitecture                                 int8
Census_OSEdition                                      int8
Census_GenuineStateName                               int8
Processor                                             int8
SmartScreen                                           int8
Census_OSInstallTypeName                              int8
Census_OSWUAutoUpdateOptionsName                      int8
Census_ChassisTypeName                                int8
Census_MDC2FormFactor                                 int8
Census_ActivationChannel                              int8
Census_PowerPlatformRoleName                          int8
Census_InternalPrimaryDiagonalDisplaySizeInInches    int16
Census_ProcessorCoreCount                            int16
Census_HasOpticalDiskDrive                            int8
Census_IsSecureBootEnabled                            int8
Firewall                                             int16
IsProtected                                          int16
IsSxsPassiveMode                                      int8
Wdft_IsGamer                                         int16
monitor_dims                                         int16
SmartScreen_AVProductsInstalled                       int8
dtype: object

In [0]:
train[cat_features].head(20)

    OsPlatformSubRelease  ...  SmartScreen_AVProductsInstalled
0                      4  ...                               42
1                      4  ...                               42
2                      4  ...                               34
3                      4  ...                                8
4                      4  ...                               34
5                      4  ...                               34
6                      4  ...                               43
7                      1  ...                               34
8                      4  ...                               34
9                      3  ...                               35
10                     4  ...                               42
11                     4  ...                               43
12                     4  ...                               43
13                     4  ...                               34
14                     4  ...                               16
15                     4  ...                                9
16                     7  ...                               42
17                     3  ...                               42
18                     4  ...                               42
19                     3  ...                               35

[20 rows x 28 columns]

In [0]:
for i in cat_features :
  if(test[i].dtype == np.float16):
    test[i] = test[i].round(0)
    test[i] = test[i].astype('int16')

In [0]:
test[cat_features].dtypes

OsPlatformSubRelease                                  int8
Census_MDC2FormFactor_new                             int8
Census_FlightRing                                     int8
Census_PrimaryDiskTypeName                            int8
Census_OSSkuName                                      int8
Census_OSBranch                                       int8
SkuEdition                                            int8
Census_OSArchitecture                                 int8
Census_OSEdition                                      int8
Census_GenuineStateName                               int8
Processor                                             int8
SmartScreen                                           int8
Census_OSInstallTypeName                              int8
Census_OSWUAutoUpdateOptionsName                      int8
Census_ChassisTypeName                                int8
Census_MDC2FormFactor                                 int8
Census_ActivationChannel                              int8
Census_PowerPlatformRoleName                          int8
Census_InternalPrimaryDiagonalDisplaySizeInInches    int16
Census_ProcessorCoreCount                            int16
Census_HasOpticalDiskDrive                            int8
Census_IsSecureBootEnabled                            int8
Firewall                                             int16
IsProtected                                          int16
IsSxsPassiveMode                                      int8
Wdft_IsGamer                                         int16
monitor_dims                                         int16
SmartScreen_AVProductsInstalled                       int8
dtype: object

In [0]:
data = train_test_split(train, train_labels, test_size=0.2, random_state=20)
X_train, X_validation, y_train, y_validation = data

In [0]:
train_pool = Pool(
    data=X_train, 
    label=y_train, 
    cat_features=cat_features)

validation_pool = Pool(
    data=X_validation, 
    label=y_validation, 
    cat_features=cat_features
)

**Model 2**

In [0]:
model = CatBoostClassifier(iterations=10, learning_rate=0.003)

In [0]:
model.fit(train_pool, eval_set=validation_pool, verbose = False)

In [0]:
y_pred = model.predict_proba(test)[:, 1]

In [0]:
submission = pd.DataFrame({data_id: test_ids, target: y_pred})

In [0]:
sub_path = '/content/gdrive/My Drive/kaggle/ms/submission_v2.csv'

In [0]:
submission.to_csv(sub_path, index = False)